Implemented social class
CSC207-UofT/plannr pull request #15
Opened 2021-11-08 21:53 UTC by OKok-3

Added setter methods to suppress IntelliJ's "make this final" suggestions, and made the ArrayList of participants final as suggested.

Made participants final because this way we eliminate the risk of accidentally assigning the name participants to something else, i.e. the variable "participants" is now bind with the ArrayList that has all the participants. See this StackOverflow answer for more: https://stackoverflow.com/questions/10750791/what-is-the-sense-of-final-arraylist

2021-11-08 22:10 UTC, sarihammad requested changes
Everything looks good! Although I think participants should not be final since by definition final means it cannot be changed which it can through the setter method. I would suggest leaving the 'make this final' for the participants if it can't be suppressed.

2021-11-08 22:17 UTC, OKok-3 commented
@sarihammad I just tested the final keyword in a scratch file and it seems to be working with ArrayList. I think the "final" keyword only binds the variable name and the object together, imagine drawing a permanent arrow from the variable name to the object. So it wouldn't interfere with modifying the ArrayList itself.

Would you mind double checking to see if I understood this correctly? Thanks!

2021-11-08 22:24 UTC, sarihammad approved these changes
Yes, I think you're right. That's also what I understood from the StackOverflow answer. Just ignore my recent change request.

2021-11-10 17:17 UTC, cdw18 approved these changes

2021-11-10 17:18 UTC, merged