main-page
CSC207-UofT/plannr pull request #25
Opened 2021-11-13 17:27 UTC by hellokathylee

2021-11-13 17:53 UTC, EvgeniaSila approved these changes, later dismissed
Looks so good!

2021-11-13 17:53 UTC, EvgeniaSila commented on Uni_life_tracker/app/src/main/res/layout/activity_main.xml
> +            android:text="@string/app_name"
Minor detail: but would it be possible to change the font to roboto_mono and roboto_mono_bold where needed

2021-11-14 06:37 UTC, dalshekerchi requested changes

2021-11-14 06:37 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/res/layout/main_nav_drawer.xml
> +    <LinearLayout android:layout_width="match_parent"
You have a couple of styling errors in this file that say "This tag and its children can be replaced by one `<TextView/>` and a compound drawable"

2021-11-14 06:37 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/res/layout/main_nav_drawer.xml
> +    <LinearLayout android:layout_width="match_parent"
Same here

2021-11-14 06:37 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/res/layout/main_nav_drawer.xml
> +    <LinearLayout android:layout_width="match_parent"
Here as well

2021-11-14 06:37 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/res/layout/main_nav_drawer.xml
> +    <LinearLayout android:layout_width="match_parent"
And this

2021-11-14 06:37 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/res/layout/main_menu.xml
> +<!--    <TextView-->
Do you need this commented code here?

2021-11-14 06:40 UTC, dalshekerchi requested changes

2021-11-14 06:40 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/java/com/generic/ult/recyclerAdapter.java
> +public class recyclerAdapter extends RecyclerView.Adapter<recyclerAdapter.MyViewHolder>{
The same of the class should be RecyclerAdapter, make sure to refactor when renaming

2021-11-14 06:40 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/res/layout/list_events.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Do you want to make this activity a LinearLayout like the other ones

2021-11-14 07:53 UTC, dalshekerchi submitted a review, later dismissed

2021-11-14 08:14 UTC, dalshekerchi approved these changes

2021-11-14 08:14 UTC, merged