Add income
CSC207-UofT/plannr pull request #79
Opened 2021-12-04 20:48 UTC by EvgeniaSila

- Created add income box and save income button 
- added total sum display 
- created methods to be later completed for calulcating total expenses

2021-12-04 21:30 UTC, hellokathylee submitted a review, later dismissed

2021-12-05 01:32 UTC, dalshekerchi requested changes

2021-12-05 01:32 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
> +
Can you add javadocs here

2021-12-05 01:32 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
> +
Here as well

2021-12-05 06:29 UTC, EvgeniaSila commented on Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
> +
got it

2021-12-05 06:29 UTC, EvgeniaSila commented on Uni_life_tracker/app/src/main/java/com/generic/plannr/ExpensesActivity.java
> +
fixed

2021-12-05 06:29 UTC, merged