reformat and documentation
CSC207-UofT/plannr pull request #82
Opened 2021-12-05 02:54 UTC by hellokathylee

- add and modify javadocs
- implement add expenses prompt
- set app default font, colour
- modify text formatting for currency
- delete unused files
- disable back from previous activities

2021-12-05 06:25 UTC, EvgeniaSila approved these changes, later dismissed

2021-12-05 19:20 UTC, dalshekerchi requested changes
Merge in main into you branch because I think that you might get some merge conflicts

2021-12-05 19:20 UTC, dalshekerchi commented on Uni_life_tracker/app/src/main/java/com/generic/plannr/SchoolActivity.java
> -        Intent intent = new Intent(this, MainPageActivity.class);
Maybe change this to use the redirect function

2021-12-06 01:20 UTC, dalshekerchi approved these changes

2021-12-06 01:21 UTC, merged