edit password
CSC207-UofT/plannr pull request #83
Opened 2021-12-05 04:55 UTC by dalshekerchi

- deleted uni attributes from user as it was not being used 
- added changing of password functionality to settings page

2021-12-05 06:25 UTC, EvgeniaSila submitted a review, later dismissed

2021-12-05 16:38 UTC, hellokathylee requested changes
i think there is a bug w validating password in settings- as long as its over 6 characters it is approved when i tried it (so like kathyy or kathy1 would be able to save for me)

2021-12-06 03:32 UTC, hellokathylee approved these changes
works!!!

2021-12-06 03:41 UTC, cdw18 approved these changes
Looks good!

2021-12-06 03:41 UTC, merged